changelog:
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - bugfix
          - breaking
    - title: 👒 Dependencies
      labels:
        - dependencies
    - title: 🐛 Bugfixes
      labels:
        - bugfix
    - title: 🔨 Breaking Changes
      labels:
        - breaking
