language: python
python:
- '3.8'
- '3.9'
- '3.10'
dist: bionic
sudo: true
matrix:
  fast_finish: true
install:
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U importlib_metadata;
  fi
- pip install coverage coveralls
- pip install black
- pip install -e .
script:
- black --check .
- coverage run --source=uplc setup.py test
after_success:
- coverage report
- coveralls
deploy:
  provider: pypi
  on:
    branch: master
    python: '3.10'
  distributions: sdist bdist_wheel
  skip_existing: true
  username: nielstron
  password:
    secure: zWc93BSL9C76B0kmxSiy7mGS3XIkXsRtA+dZHJ32wcmXTd3d/HLLo4hJqvYHTGp5PALy0UUglo4U+m819AyUsNcEVAoDNvBGMFd/wlb03/P+/akeACTbA0geFnPc/OO1gpxJk9UeaD8GC3FvNGftE4k6bB76YEjFGccKe1JJFAG4uFerzwSr9Kd3B09XgxcLR9KTP3TZFduKwTt/wgDw9Ma48Qecn1k4Ho3Gtp7qgmYozFEVcEjbJRVXRR6mtGOXqtIp3QZyNmqK3cCENEYMRxoFPpzbHaFlYPX+C3wXFOt5TgXareymWEMJM35h2bs7SEsCKvEelDZpze3gjADlifsaMMdNGJX5ZRnzxe+m9eOG2mFNEDpqtnlzA80PCC6O603V4/74QAWiQUsho11LnlQsMndKpG6K03kXXGnsasPlKYBImgXkCkV165UFSFWi91vY0+RpdD1pSAewC30J37/ADSGBN+0V/zJ4xCjjFTKfTry1DZgjcKZBIH+zIwEyX8U5RRgkMy+8mzW6yYda5OaPeVg+I1ppnq9eyty10sUoc7dNhfNjGDbxAKFBERfSubL0/pqqKKeCAvHp9AeaUBgW23Zpkr/sB1VDPgyr7QA4O7OoAubnvirryNYgrhTNQKbeFh5QeQgpV13/LNTGHTjOywyHWXorGbpROd2sJu8=
