language: python
python:
- '3.8'
- '3.9'
- '3.10'
- '3.11'
dist: bionic
os: linux
arch:
  - arm64
jobs:
  fast_finish: true
before_install:
- bash install_secp256k1.sh
- LD_LIBRARY_PATH=/usr/local/lib:"$LD_LIBRARY_PATH"
- export LD_LIBRARY_PATH
- pip install poetry
install:
- poetry install
script:
- black --check .
- coverage run --source=uplc -m pytest uplc/tests
- coverage run -a --source=uplc -m uplc parse examples/fibonacci.uplc
- coverage run -a --source=uplc -m uplc dump examples/fibonacci.uplc --dialect legacy-aiken
- coverage run -a --source=uplc -m uplc dump examples/fibonacci.uplc --dialect plutus --unique-varnames
- coverage run -a --source=uplc -m uplc eval examples/fibonacci.uplc "(con integer 5)"
- coverage run -a --source=uplc -m uplc build examples/fibonacci.uplc
- coverage run -a --source=uplc -m uplc build examples/fibonacci.uplc -fremove-traces
- coverage run -a --source=uplc -m uplc build examples/fibonacci.uplc -fconstant-folding
- coverage run -a --source=uplc -m uplc dump build/fibonacci/script.cbor --from-cbor
after_success:
- coverage report
- coveralls
deploy:
  provider: script
  on:
    tags: true
    python: '3.10'
    repo: OpShin/uplc
  script: poetry publish --username __token__ --password $PYPI_PASS --build
