name: Python package
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # If there isn't a release for this version, create a new one.
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          makeLatest: true
          prerelease: true
          skipIfReleaseExists: true
      # Build and publish the package to pypi.
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: "3.10"
          pypi_token: ${{ secrets.PYPI_PASSWORD }}
          package_directory: "uplc"
          poetry_install_options: "--without dev"
